config/routes.rb
Rails.application.routes.draw do
  root 'providers#search'

  get '/provider_search', to: 'providers#search'
  get '/provider_results', to: 'providers#index'
  get '/search_tips', to: 'providers#search_tips'
end

# consider more specific naming for search route

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # rescue_from StandardError, with: :add_search_criteria
  helper_method :flash_message
  # def add_search_criteria
  #   flash[:error] = message
  #   redirect_back(fallback_location: provider_search_path)
  # end
  #
  def flash_message
    'At least one the the following fields
    below must be completed in addition to
    State: First Name, Last Name, or Specialty.'
  end
end

app/controllers/providers_controller.rb
require 'will_paginate/array'

class ProvidersController < ApplicationController
  def search;end

  def index
    begin
      array = call_provider_facade
    rescue => e
      flash[:alert] = flash_message
      redirect_to provider_search_path
    end
    return @providers = array.paginate(page: params[:page], per_page: 20) if !array.nil?
  end

  private
  def call_provider_facade
    ProviderFacade.provider_data(params[:first_name], params[:last_name], params[:specialty], params[:state])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProviderFinder</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |type, msg| %>
      <div class="alert alert-info">
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/providers/index.html.erb
<div class="container pt-5">
  <div class="d-grid">
    <div class="btn btn-warning">
      <%= link_to 'Back to provider search page', provider_search_path, :class => "btn" %>
    </div>
  </div>

  <br>

  <div class="container p-1 my-1 border border-warning border-2">
    <h2 class="text-center">Provider Search Results:</h2>
  </div>

  <br>

  <% if params[:last_name] && params[:state] %>
    <% @providers.each do |provider| %>
      <dt><p><%= provider.full_name %></p></dt>
      <p><strong class="text-primary">NPI Number: </strong><%= provider.npi_number %></p>
      <p><strong class="text-primary">Specialty: </strong><%= provider.specialty %></p>
      <p><strong class="text-primary">Address: </strong><%= provider.addresses %></p>
      <p><strong class="text-primary">Phone Number: </strong><%= provider.phone %></p>
      <hr class="dashed">
    <% end %>
  <% end %>

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"></script>
  </head>
  <body>
    <div class="container p-1 my-1 border border-warning border-2">
      <p class="text-center"><%= page_entries_info @providers %></p>
      <p class="text-center"><%= will_paginate @providers, renderer: BootstrapPagination::Rails %></p>
    </div>
  </body>
</div>

app/views/providers/search.html.erb
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container pt-3">
  <div class="container p-1 my-1 border border-warning border-2">
    <h2 class="text-center">Search for a provider</h2>
  </div>

  <div class="pt-3">
    <p>For some ideas on how to get back the best results for you search, please see the <%= link_to 'Search Tips', search_tips_path, method: :get, target: :_blank %></p>
  </div>
    <div class="m-1 pb-5">
      <%= bootstrap_form_with url: provider_results_path, method: :get, local: true do |form| %>
        <strong><%= form.text_area :first_name, label: "First Name:", hide_label: false, placeholder: "Enter provider first name here" %></strong>
        <strong><%= form.text_area :last_name, label: "Last Name:", hide_label: false, placeholder: "Enter provider last name here" %></strong>
        <strong><%= form.text_area :specialty, label: "Specialty or area of practice:", hide_label: false, placeholder: "Enter specialty here, eg. 'dental'" %></strong>
        <strong><%= form.text_area :state, label: "Provider location by State:", hide_label: false, placeholder: "Enter state abbreviation here, eg. 'CO'. Please also include at least one of the other search options above: First Name, Last Name, or Specialty" %></strong>
        <%= form.submit 'Find me a provider!' %>
      <% end %>
    </div>
  </div>
</body>

app/views/providers/search_tips.html.erb
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<div class="container">
  <style>
    ul.a {
      list-style-type: circle;
    }
  </style>

  <div class="pt-3">
    <div class="container p-1 my-1 border border-warning border-2">
      <h2 class="text-center">Provider Search Tips</h2>
    </div>
  </div>

  <div class="pt-3">
    <h4>What is a provider anyway?</h4>
  </div>

  <ul class="a">
    <li>In healthcare, a provider is a person or company that provides a healthcare service to you. </li>
    <li>Examples of individual providers are doctors and dentists to physical therapists and mental health professionals. There are many types!</li>
    <li>Again, this could refer to one professional but also to an entire group or company of professionals (such as at a healthcare center).</li>
  </ul>

  <div class="pt-3">
    <h5>For best results, it is recommended to use the following combinations for your provider search:</h5>
  </div>

  <ul class="a">
    <li>Last Name + State </li>
    <li>First Name + Last Name</li>
    <li>Speciality + State</li>
  </ul>


  <div class="pt-3">
    <h5 class="text-danger">Important Notes</h5>
  </div>

  <ul class="a">
    <li>For state, you must use the state abbreviations. Examples: CO for Colorado or TX for Texas</li>
    <li>For specialty, please try to put the exact name of the speciality service you are looking for. This will help return more accurate results. Examples: 'Family Medicine' or 'Dietitian'</li>
    <li>If you aren't sure of the exact name of the speciality, try different things! For exmaple, you will get different results from 'dentist' and 'dental'</li>
  </ul>

  <div class="m-1 pt-3 pb-5">
    <div class="btn btn-warning">
      <%= link_to 'Back to provider search page', provider_search_path, :class => "btn" %>
    </div>
  </div>
</div>